version: '3.7'

services:
  gotest:
    container_name: gotest
    build:
      context: '.'
      dockerfile: Dockerfile
      target: dev
    # depends_on:
    #   - loki
    restart: always
    ports: 
      - "5000:5000"
    volumes:
      - ./cmd:/go/cmd
    
